version: '3.8'

services:
  web:
    build: .
    container_name: navigation-page
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # 挂载动态文件以便开发时实时更新
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./style.css:/usr/share/nginx/html/style.css:ro
      - ./js:/usr/share/nginx/html/js:ro
      - ./game:/usr/share/nginx/html/game:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - navigation-net

networks:
  navigation-net:
    driver: bridge
